[blockchain]
project_name = "XferMoney"
headline = "Peer-To-Peer remittance platform"
short_description = "Xfermoney platform is designed to disrupt and replace the traditional way of money transfers by connecting peers via the platform in different countries to exchange money directly and cut down the middleman, banks or brokers plus costs associated with them."
logo = ""
state = "0"
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://xfermoney.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://xfermoney.io/wp-content/uploads/2017/12/XferMoney_Whitepaper_1.0.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Xfermoney-136308600385196"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/XferMoney"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/xfermoney"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?action=profile;u=1537294"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/user/xfermoney"
  tags = [
    "News"
  ]

  [[blockchain.milestone]]
  number = 1.0
  name = "Idea Incubation, Market Research & Feasibility Analysis, Team formation"
  start_date = "Q3 – 2017"
  end_date = "Q4 – 2017"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 2.0
  name = "Whitepaper Release, Platform Architecture & Design"
  start_date = "Q4 – 2017"
  end_date = "Q1 – 2018"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 3.0
  name = "XFM Token Offerings, Brand Awareness, Exchange Listing, Platform Development, Team Expansion"
  start_date = "Q1 – 2018"
  end_date = "Q2 – 2018"
  current_status = "In work"
  value = false

  [[blockchain.milestone]]
  number = 4.0
  name = "Platform Development, Obtain Regional Licenses & Approvals  "
  start_date = "Q2 – 2018"
  end_date = "Q3 – 2018"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 5.0
  name = "Alpha Release, Basket 1 Currency pairs"
  start_date = "Q3 – 2018"
  end_date = "Q4 – 2018"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 6.0
  name = "Beta Launch, BASKET 1 and 2 Currency pairs"
  start_date = "Q4 – 2018"
  end_date = "Q1 – 2019"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 7.0
  name = "Launch of Multi-currency Debit Card, Support for new currency pairs"
  start_date = " Q2 – 2019"
  end_date = " Q3 – 2019"
  current_status = "Planned"
  value = false

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  current_phase_status = ""

    [ico.common_info.token_distribution]
    total_supply = "250000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "XferMoney Team and Founders"

      [[ico.common_info.token_distribution.shares]]
      percent = "70"
      description = "Token Sale"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Marketing Campaign"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Advisors"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Opretional Overhead"

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Platform Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Licences & Approvals"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Business Developemt"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Reserves"

  [[ico.phases]]
  phase_name = "crowdsale"
  phase_status = "Active"
  phase_num = 0.0

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    sales_agreement = "https://xfermoney.io/documents/XferMoney_Whitepaper_1.0.pdf"
    sales_url = "https://xfermoney.io/tokensale/"
    issued_tokens = "250000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "5000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-02-16T00:00:00.000Z"
    end_date = "2018-03-31T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "ETH"
      price = 0.0

      [[ico.phases.prices.bonuses]]
      amount = "40%"
      condition = "first 3 days of tokensale"
      index = 0.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "25%"
      condition = "Week 1"
      index = 1.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "18%"
      condition = "Week 2"
      index = 2.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "week 3"
      index = 3.0
      value = false

[app]
info = []

[[token]]
inflation_rate = ""
circulation_terms = ""
governance_rights_org = ""
governance_rights_project = "Ownership of XFM carries no rights other than the right to exchange and claim over\nthe platform. XFM does not represent or confer any ownership right or stake, share\nor security or equivalent rights, intellectual property rights or any other form of\nparticipation relating to the XferMoney Platform."
name = "XFM"
symbol = "XFM"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"

[[exchange]]
exchange = ""
date = ""
price = ""
volume = ""

[[label]]
blockchain = ""
address = ""
balance = ""