[blockchain]
project_name = "TON"
headline = "The most powerful infrastructure Telegram."
short_description = "Телеграм запускает TON(Telegram Open Network)-быструю , масштабируемую и удобную для пользователей крипто валюта и блокчейн платформу .Каждый пользователь Телеграм получит TON-кошелёк ,тем самым данная цифровая валюта имеет шансы стать самой распространённой в мире . Благодаря своей уникальной архитектуре, TON способна безопасно обрабатывать миллионы транзакций в секунду. Когда блокчейн TON становится слишком большим он автоматически разделяется на два, чтобы увеличить пропускную способность. Все блокчейны TON могут быстро обмениваться данными используя умную систему маршрутизации.TON использует каналы прямых платежей для перевода средств в течении миллисекунд. Любой блок из блокчейна TON может стать самостоятельным блокчейном, что делает всю структуру невероятно гибкой .\n"
logo = ""
state = "0"
dependency = "independent"
consensus_name = "Unknown"

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/ico_telegram"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://tongram.info/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://tongram.info/whitepaper/gram_whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.milestone]]
  number = 1.0
  name = "Project concept created"
  start_date = "2017-04-01"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 2.0
  name = "Platform development launched"
  start_date = "2017-05-01"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 3.0
  name = "Token model approved"
  start_date = "2017-09-01"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 4.0
  name = "Closed platform testing"
  start_date = "2017-10-01"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 5.0
  name = "Close testing of GRAM token"
  start_date = "2017-11-01"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 6.0
  name = "Pre-ICO"
  start_date = "2018-01-01"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 7.0
  name = "ICO"
  start_date = "2018-02-01"
  current_status = "In work"
  value = false

  [[blockchain.milestone]]
  number = 8.0
  name = "Token withdrawal and Exchange Listing"
  start_date = "2017-03-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 9.0
  name = "Telegram Open Network Testing"
  start_date = "2018-05-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 10.0
  name = "Telegram App Big Update to use GRAM token"
  start_date = "2018-07-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 11.0
  name = "Mass apply TON to 200M users of Telegram"
  start_date = "2018-08-01"
  current_status = "Planned"
  value = false

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 1.0
  current_phase_status = ""

    [ico.common_info.token_distribution]
    total_supply = " 5000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "4"
      description = "4-year vesting by developers"

      [[ico.common_info.token_distribution.shares]]
      percent = "44"
      description = "potentially sold investors"

      [[ico.common_info.token_distribution.shares]]
      percent = "52"
      description = "retained by the TON Reserve"

    [[ico.common_info.use_of_proceeds]]
    description = ""
    percent = 0.0

  [[ico.phases]]
  phase_name = "Pre-ICO"
  phase_status = "Finished"
  phase_num = 0.0

    [ico.phases.registration]
    start_date = "2018-01-01T00:00:00.000Z"
    end_date = "2018-01-31T00:00:00.000Z"
    website = "https://tongram.info/get/"
    terms = "https://tongram.info/get/"

    [ico.phases.terms]
    sales_agreement = "https://tongram.info/get/"
    sales_url = "https://tongram.info/get/"
    issued_tokens = 0.0
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = 0.0

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-01-01T00:00:00.000Z"
    end_date = "2018-01-31T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "USD"
      price = "0.38"

      [[ico.phases.prices.bonuses]]
      amount = "+2% bonus"
      condition = "for purchase of $2000"
      index = 0.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+5% bonus"
      condition = "for purchase of $5000"
      index = 1.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+10% bonus"
      condition = "for purchase of $10000"
      index = 2.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+25% bonus"
      condition = "for purchase of $20000"
      index = 3.0
      value = false

  [[ico.phases]]
  phase_name = "Pre-ICO"
  phase_status = "Finished"
  phase_num = 1.0

    [ico.phases.registration]
    start_date = "2018-01-01T00:00:00.000Z"
    end_date = "2018-01-31T00:00:00.000Z"
    website = "https://tongram.info/get/"
    terms = "https://tongram.info/get/"

    [ico.phases.terms]
    sales_agreement = "https://tongram.info/get/"
    sales_url = "https://tongram.info/get/"
    issued_tokens = "12000000"
    sold_tokens = "10680000"
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "850000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-01-01T00:00:00.000Z"
    end_date = "2018-01-31T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "USD"
      price = "0.4"

      [[ico.phases.prices.bonuses]]
      amount = "+2% bonus"
      condition = "for purchase of $2000"
      index = 0.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+5% bonus"
      condition = "for purchase of $5000"
      index = 1.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+10% bonus"
      condition = "for purchase of $10000"
      index = 2.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+25% bonus"
      condition = "for purchase of $20000"
      index = 3.0
      value = false

[app]

  [[app.info]]
  name = "Telegram"
  same = "true"
  availability = "false"
  status = "3"
  app_type = "Web App, Mobile App"
  app_url = "https://telegram.org"

[[token]]
inflation_rate = ""
circulation_terms = " Commission («gas») paid to TON nodes («validators») for processing transactions\nand smart contracts;"
governance_rights_org = "Voting power required to support or oppose changes in the parameters\nof the protocol;"
governance_rights_project = ""
name = "GRAM "
symbol = "GRAM "
token_purpose = "Utility"
token_type = "Core token"

[[exchange]]
exchange = ""
date = ""
price = ""
volume = ""

[[label]]
blockchain = ""
address = ""
balance = ""